#server:
#  port: 8443
#  ssl:
#    key-store: var/conf/keystore.p12
##    key-store-password: pwd123
#    keyStoreType: PKCS12
#    keyAlias: tomcat

#eureka:         
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
 
spring:    
  application:
    name: service-backend