server:
  port: 8080

eureka:         
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    preferIpAddress: true 
spring:    
  application:
    name: service-frontend
